"""empty message

Revision ID: d316c6f8fe2e
Revises: 
Create Date: 2021-05-15 13:57:16.202866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd316c6f8fe2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycle',
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('exhaust', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycle')
    # ### end Alembic commands ###
